RGZ/rails-app/config/routes.rb
Rails.application.routes.draw do
  root 'lab_reports#index'

  resources :lab_reports
  resources :users

  get '/LabReports/:id/mark', to: 'lab_reports#mark', as: 'mark_lab_report'
  post '/LabReports/:id/mark', to: 'lab_reports#grade'
  get '/Users/:id', to: 'users#show'
end

RGZ/rails-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RGZ/rails-app/app/models/lab_report.rb
class LabReport < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 250 }
  validates :description, length: { maximum: 250 }
end

RGZ/rails-app/app/models/user.rb
class User < ApplicationRecord
  has_many :lab_reports

  validates :first_name, presence: true, length: { maximum: 100 }
  validates :last_name, presence: true, length: { maximum: 100 }
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
end

RGZ/rails-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling
end

RGZ/rails-app/app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

RGZ/rails-app/app/controllers/lab_reports_controller.rb
class LabReportsController < ApplicationController

    def index
      @lab_reports = LabReport.all
    end

    def show
      @lab_report=LabReport.find(params[:id])
    end

    def new
      @lab_report = LabReport.new
    end

    def create
      lab=LabReport.new(params.require(:lab_report).permit(:title,:description))
      lab.user_id=1
      if lab.save
        redirect_to root_url
        flash[:success] = "Lab report was added"
      else
        redirect_to root_path
        flash[:DANGER] = "Some error occured"
      end
    end

    def edit
      @lab_report=LabReport.find(params[:id])
    end

    def update
      @lab_report=LabReport.find(params[:id])
      if @lab_report.update(params.require(:lab_report).permit(:title,:description))
        redirect_to root_url
        flash[:success] = "Lab was updated successfully"
      else
        render :edit
        flash[:DANGER] = "Some error occured"
      end
    end

    def mark
      @lab_report=LabReport.find(params[:id])
    end

    def grade
      @lab_report=LabReport.find(params[:id])
      if @lab_report.update(params.permit(:grade))
        redirect_to root_url
        flash[:success] = "Mark was added successfully"
      else
        render :mark
        flash[:DANGER] = "Some error occured"
      end
    end

    def destroy
      @lab_report=LabReport.find(params[:id])
      @lab_report.destroy
      redirect_to action: :index
      flash[:success] = "Lab was deleted successfully"
    end

end

RGZ/rails-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user=User.find(params[:id])
  end
end

RGZ/rails-app/app/helpers/application_helper.rb
module ApplicationHelper
end

RGZ/rails-app/app/helpers/lab_reports_helper.rb
module LabReportsHelper
end

RGZ/rails-app/app/helpers/users_helper.rb
module UsersHelper
end

RGZ/rails-app/app/views/lab_reports/_form.html.erb
<%= form_with model: @lab_report do |f|%>
  <% if @lab_report.errors.any?%>
    <% @lab_report.errors.full_messages.each do |msg|%>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <h4>Title</h4>
    <%= f.text_field :title, required: true%><br>

  <h4>Description</h4>
    <%= f.text_area :description, {:class => 'form-control'}%><br>

    <%= f.submit({:class => 'btn btn-success'}) %>
    <%= link_to 'Назад', root_path, class: 'btn btn-secondary' %>
<% end %>

RGZ/rails-app/app/views/lab_reports/edit.html.erb
<h2>Редактировать лабораторный отчёт</h2><br>

<%= render 'form' %>

RGZ/rails-app/app/views/lab_reports/index.html.erb
<h1>Лабораторные отчёты</h1><br>


<%= link_to 'Загрузить лабороторный отчёт', new_lab_report_path, class: 'btn btn-outline-primary' %>
<br><br>

<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>

<div class="row">
  <% @lab_reports.each do |lab_report| %>
<!--      <td><%#= lab_report.user_id %></td>-->
    <div class="col">
      <div class="card border-dark mb-3" style="max-width: 18rem;">
        <div class="card-header bg-transparent border-dark">
          <%= lab_report.title %>
        </div>
        <div class="card-body text-dark">
          <h5 class="card-title">Содержимое:</h5>
          <p class="card-text"><%= lab_report.description %></p>
        </div>
        <div class="card-footer bg-transparent border-success">Оценка: <%= lab_report.grade %></div>
        <%= link_to 'Редактировать', edit_lab_report_path(lab_report), class: 'btn btn-outline-primary' %>
        <%= link_to 'Просмотр', lab_report_path(lab_report), class: 'btn btn-outline-info' %>
        <%= link_to 'Поставить оценку', mark_lab_report_path(lab_report), class: 'btn btn-outline-warning' %>
        <%= link_to 'Удалить', lab_report_path(lab_report), method: :delete, data: {confirm: "Вы уверены?"}, class: 'btn btn-outline-danger' %>
      </div>
    </div>
  <% end %>
</div>

RGZ/rails-app/app/views/lab_reports/mark.html.erb
<h2>Поставить оценку</h2><br>

<%= form_with url: mark_lab_report_path(@lab_report) do |f| %>
  <% if @lab_report.errors.any?%>
    <% @lab_report.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <h4>Grade</h4>
    <%= f.select :grade, [["A", "A"], ["B", "B"], ["C", "C"], ["D", "D"], ["E", "E"], ["FX", "FX"], ["F", "F"]] %>
    <%= f.submit({:class => 'btn btn-success'}) %>
    <%= link_to 'Назад', root_path, class: 'btn btn-secondary' %>
<% end %>

RGZ/rails-app/app/views/lab_reports/new.html.erb
<h2>Загрузить лабораторный отчёт</h2><br>

<%= render 'form' %>

RGZ/rails-app/app/views/lab_reports/show.html.erb
<h1>Title: <%= @lab_report.title %></h1><br>
<h2>Description: <%= @lab_report.description %></h2><br>
<h2>Grade: <%= @lab_report.grade %></h2><br>
<%= link_to 'Редактировать', edit_lab_report_path(@lab_report), class: 'btn btn-outline-primary' %>
<%= link_to 'Назад', root_path, class: 'btn btn-secondary' %>
<%= link_to 'Поставить оценку', mark_lab_report_path, class: 'btn btn-warning' %>

RGZ/rails-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab reports</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      a {
       text-decoration: none;
       color: black
      }
   </style>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

RGZ/rails-app/app/views/users/index.html.erb
<tbody>
<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.first_name %></td>

  </tr>
<% end %>
</tbody>

RGZ/rails-app/app/views/users/show.html.erb
<h1>Title: <%= @user.first_name %></h1><br>